parameters:
    open_orchestra_group.generate_perimeter.folder.class: OpenOrchestra\MediaAdminBundle\GeneratePerimeter\Strategy\FolderGeneratePerimeterStrategy

services:
    open_orchestra_group.generate_perimeter.folder:
        class: '%open_orchestra_group.generate_perimeter.folder.class%'
        arguments:
            - '@open_orchestra_media.repository.media_folder'
            - '@open_orchestra_backoffice.manager.multi_languages_choice'
        tags:
            - { name: open_orchestra_group.generate_perimeter.strategy }
