parameters:
     open_orchestra_media_admin.listener.update_media_folder_group_role.class: OpenOrchestra\MediaAdminBundle\EventListener\UpdateMediaFolderGroupRoleListener

services:
    open_orchestra_media_admin.listener.update_media_folder_group_role:
        class: %open_orchestra_media_admin.listener.update_media_folder_group_role.class%
        arguments:
            - %open_orchestra_media.document.folder.class%
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: preUpdate }
