contents:
    orchestra_media:
        # Describe here where the orchestra_media form type is used
        # content type: array of attributes of orchestra_media form type
        news: [image]
    tinymce:
        # Describe here where the tinymce form type is used
        # content type: array of attributes of tinymce form type
        news: [text]

blocks:
    orchestra_media:
        # Describe here where the orchestra_media form type is used
        # bloc component name: array of attributes of orchestra_media form type or collection of orchestra_media
        display_media: [picture]
        gallery: [pictures]
        slideshow: [pictures]
    tinymce:
        # Describe here where the tinymce form type is used
        # bloc component name: array of attributes of tinymce form type
        tiny_mce_wysiwyg: [htmlContent]

# If you are updating from 1.1-alphax, you can map your custom strategies here
# Otherwise, don't touch this 
media_types:
    # mime type fragment: associated custom mediaType
    image: image
    audio: audio
    'application\/pdf': pdf
    video: video
